### ISSUE TITLE
Spreadsheets editor can't scroll on Android

### ISSUE THREAD

**Issue by mobitar** [standardnotes/bounties#34] opened 2019-06-28 14:02 UTC
Works fine on desktop and iOS, but on Android, I'm getting reports that the sheet is not scrollable/pannable at all. Might just be the viewport meta tag.

**Comment by dagjaneiro** [comment] 2019-07-13 11:06
This is a known bug in the library: https://github.com/telerik/kendo-ui-core/issues/2929. It looks like it was fixed in the latest release (2019.R2.SP1). 

I won't be able to test it myself since I don't have access to the Kendo UI bundle.

**Comment by dagjaneiro** [comment] 2019-07-13 22:54
I can confirm the issue as been fixed. I've opened a PR that upgrades the lib using a custom build to the latest stable version.

**Closed** 2019-07-14 17:21 UTC
Labels: $100
